name: Check and Update KeplerGL Version

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  check_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for pushing changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create requirements.txt
        run: |
          echo "requests==2.31.0" > requirements.txt

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install requests
        run: pip install requests

      - name: Check for new version
        id: check_version
        run: |
          python check_version.py
          cat version_output.txt >> $GITHUB_ENV

      # Only run the following steps if a new version is found
      - name: Login to Docker Hub
        if: env.new_version_found == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Commit changes
        if: env.new_version_found == 'true'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Dockerfile
          git commit -m "Update keplergl version to ${{ env.latest_version }}"
          git push
        continue-on-error: true

      - name: Set up Docker Buildx
        if: env.new_version_found == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        if: env.new_version_found == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/keplergl-jupyter:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/keplergl-jupyter:${{ env.latest_version }}
